# Generated by Django 4.1.4 on 2023-03-05 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_web', '0003_alter_post_body_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='PostVideos',
            fields=[
                ('post_video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='post_videos')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_web.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostUrls',
            fields=[
                ('post_url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_web.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('post_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='post_pictures')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_web.post')),
            ],
        ),
        migrations.CreateModel(
            name='CommentImages',
            fields=[
                ('post_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='post_pictures')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_web.post')),
            ],
        ),
    ]
